packages:
  - scripts

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@ugrc/*'

overrides:
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'

allowBuilds:
  esbuild: true
  sharp: true
