name: Issue opened (new incident)

permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened]

jobs:
  open-pr:
    name: Create new incident post
    runs-on: ubuntu-latest
    steps:
      - name: 🎬 Update status
        id: update_status
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              content: 'eyes'
            });

            return response.data.id;
      - name: 🛑 Stop if not member
        if: ${{ github.event.issue.author_association != 'OWNER' && github.event.issue.author_association != 'MEMBER' }}
        run: |
          echo "You cannot run this job."
          exit 86

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: 🧰 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: 📦 Install script dependencies
        working-directory: scripts
        run: pnpm install --frozen-lockfile

      - name: 📝 Create new incident
        working-directory: scripts
        run: node new-incident.js ${{ github.event.issue.number }}

      - name: 📌 Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: create new incident post"
          title: "feat: create new incident post"
          body: |
            This PR was automatically created by the "Issue opened (new incident)" workflow.

            closes #${{ github.event.issue.number}}
          branch: feat/new-incident-${{ github.event.issue.number }}
          draft: true

      - name: 🗑️ Remove reaction
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.deleteForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              reaction_id: ${{ steps.update_status.outputs.result }}
            })

      - name: ✅ Set complete reaction
        uses: actions/github-script@v7
        if: ${{ steps.cpr.outputs.pull-request-number }}
        with:
          script: |
            github.rest.reactions.createForIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              content: 'rocket'
            });
